from __future__ import annotations

from .effect_handlers import (
    apply_blur,
    apply_chromatic_aberration,
    apply_color_grade,
    apply_fade_black,
    apply_flash_white,
    apply_highlight,
    apply_letterbox,
    apply_solid_black,
    apply_text_overlay,
    apply_vignette,
    clamp,
    edge_envelope,
    effect_progress,
    parse_hex_color,
)
from .effect_policy import (
    effect_fallback,
    effect_sort_key,
    effect_wins,
    event_conflict_group,
    event_priority,
    event_type,
)
from .effect_registry import (
    EFFECT_ALIASES,
    EFFECT_HANDLERS,
    EFFECT_REGISTRY,
    describe_effect_event,
    effect_execution_manifest,
    event_namespace,
    normalize_event_name,
)
from .effect_runtime import apply_frame_effects, events_for_segment, is_event_active, resolve_frame_effects
from .effect_types import EffectDefinition, EffectHandler, FrameEffect, PHASE_ORDER


__all__ = [
    "EFFECT_ALIASES",
    "EFFECT_HANDLERS",
    "EFFECT_REGISTRY",
    "PHASE_ORDER",
    "EffectDefinition",
    "EffectHandler",
    "FrameEffect",
    "apply_blur",
    "apply_chromatic_aberration",
    "apply_color_grade",
    "apply_fade_black",
    "apply_flash_white",
    "apply_frame_effects",
    "apply_highlight",
    "apply_letterbox",
    "apply_solid_black",
    "apply_text_overlay",
    "apply_vignette",
    "clamp",
    "describe_effect_event",
    "edge_envelope",
    "effect_execution_manifest",
    "effect_fallback",
    "effect_progress",
    "effect_sort_key",
    "effect_wins",
    "event_conflict_group",
    "event_namespace",
    "event_priority",
    "event_type",
    "events_for_segment",
    "is_event_active",
    "normalize_event_name",
    "parse_hex_color",
    "resolve_frame_effects",
]
